### ISSUE TITLE
支持自定义文件路径

### ISSUE THREAD

**Issue by bowencool** [hamsterbase/i18nease#1]
<img width="480" alt="image" src="https://github.com/hamsterbase/i18nease/assets/20217146/10dcda7c-127d-47f7-a669-a2c1fa317367">
<img width="435" alt="image" src="https://github.com/hamsterbase/i18nease/assets/20217146/51e5e984-6501-4f9b-bc53-c49ec7d31088">

**Comment by CaryTrivett** [comment]
https://i18nease.hamsterbase.com/guide/config.html#locale-path

**Comment by CaryTrivett** [comment]
你的意思是希望自定义 local 文件的组织方式吗

**Comment by bowencool** [comment]
对啊，你看我的文件是 [lang]/xxx.json 而不是 [lang].json，仅仅配置文件夹路径是不够的

**Comment by CaryTrivett** [comment]
设置 locale_config_name 配置 `{locale}/translation.json` 即可

**Comment by bowencool** [comment]
`{locale}/translation.json` 会报错：
<img width="707" alt="image" src="https://github.com/hamsterbase/i18nease/assets/20217146/7fa48783-e09f-4eee-9cc0-ccfd2510ef0b">
随便改一下却可以 `a{locale}/translation.json`
![image](https://github.com/hamsterbase/i18nease/assets/20217146/453e1395-5616-45e3-9d1a-a5a62a9e27fb)

**Comment by CaryTrivett** [comment]
为了防止误覆盖用户代码，i18nease 加了检查。
你需要在原来的 json 文件里加上 __i18n__ease__：“true”


你随便改一个路径生成一下，就可以看到这个 key 了
